name: Build-OpenWrt-lede-b1

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '0 18 * * 0,2,4,5,6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIN_PATH: /home/runner/work/newifi3-d2-openwrt/newifi3-d2-openwrt/lede/bin

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build Environment Initialization
        run: |
          sudo apt update
          sudo apt -qq purge azure-cli ghc zulu* llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*

          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node

          sudo apt -qq autoremove --purge
          sudo apt -qq clean

          sudo apt -qq upgrade -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
            git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
            mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
            libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
            vim wget xmlto xxd zlib1g-dev re2c

      - name: Build lede
        run: |
          chmod +x build.sh && ./build.sh

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Packages-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Firmwares-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          name: immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2.manifest